
spring:
  application:
    name: cryptopay

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000 # Replace with your Authorization Server URI
server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html