spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false # Disable SQL logs in production
    format-sql: false # Disable formatted SQL logs in production
    use-new-id-generator-mappings: true
  flyway:
    enabled: true # Enable Flyway for database migrations
    locations: classpath:/db/migration

logging:
  level:
    org.springframework: WARN #
