spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/redlane-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase: classpath:db.changelog/db.changelog-master.xml
#  flyway:
#    enabled: true # Enable Flyway for database migrations
#    locations: classpath:/db/migration

logging:
  level:
    org.springframework: WARN #
